import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  weight: "variable",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "trillAcademy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClerkProvider afterSignOutUrl={"/"}>
        <html lang="en">
          <body className={`${montserrat.className} antialiased`}>
            <Toaster
              position="top-center"
              toastOptions={{
                style: { background: "#000000", color: "#ffffff" },
              }}
            />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
